/**
 * Post Store API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AiContentResponseRateLimit {
    'timeUntilRefreshSeconds'?: number;
    'usage'?: number;
    'limit'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timeUntilRefreshSeconds",
            "baseName": "timeUntilRefreshSeconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "usage",
            "baseName": "usage",
            "type": "number",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AiContentResponseRateLimit.attributeTypeMap;
    }

    public constructor() {
    }
}

