/*
 * Post Store API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)

// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface {
	AiGenerateContent(http.ResponseWriter, *http.Request)
	Delete(http.ResponseWriter, *http.Request)
	Get(http.ResponseWriter, *http.Request)
	Post(http.ResponseWriter, *http.Request)
	Put(http.ResponseWriter, *http.Request)
}

// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface {
	AiGenerateContent(context.Context, string, AiContentPostRequest) (ImplResponse, error)
	Delete(context.Context, string, string) (ImplResponse, error)
	Get(context.Context, string, string) (ImplResponse, error)
	Post(context.Context, string, CreateOrUpdatePostRequest) (ImplResponse, error)
	Put(context.Context, string, string, CreateOrUpdatePostRequest) (ImplResponse, error)
}
