/*
 * Post Store API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AiContentResponseRateLimit struct {
	TimeUntilRefreshSeconds int32 `json:"timeUntilRefreshSeconds,omitempty"`

	Usage int32 `json:"usage,omitempty"`

	Limit int32 `json:"limit,omitempty"`
}

// AssertAiContentResponseRateLimitRequired checks if the required fields are not zero-ed
func AssertAiContentResponseRateLimitRequired(obj AiContentResponseRateLimit) error {
	return nil
}

// AssertRecurseAiContentResponseRateLimitRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AiContentResponseRateLimit (e.g. [][]AiContentResponseRateLimit), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAiContentResponseRateLimitRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAiContentResponseRateLimit, ok := obj.(AiContentResponseRateLimit)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAiContentResponseRateLimitRequired(aAiContentResponseRateLimit)
	})
}
